local text = C.gray_100
local bg = C.gray_800

local base = {
	Normal = { fg = text, bg = bg },
	NormalNC = { fg = text, bg = bg },
	Comment = { fg = C.gray_500, bg = C.none, italic = true },
	Constant = { fg = text, bg = C.none },
	String = { fg = C.gray_400, bg = C.none },
	Character = { fg = text, bg = C.none },
	Number = { fg = text, bg = C.none },
	Boolean = { fg = text, bg = C.none },
	Float = { fg = text, bg = C.none },
	Identifier = { fg = text, bg = C.none },
	Function = { fg = text, bg = C.none },
	Statement = { fg = text, bg = C.none },
	Conditional = { fg = text, bg = C.none },
	Repeat = { fg = text, bg = C.none },
	Label = { fg = text, bg = C.none },
	Operator = { fg = text, bg = C.none },
	Keyword = { fg = text, bg = C.none },
	Exception = { fg = text, bg = C.none },
	Preproc = { fg = text, bg = C.none },
	Include = { fg = text, bg = C.none },
	Define = { fg = text, bg = C.none },
	Title = { fg = text, bg = C.none },
	Macro = { fg = text, bg = C.none },
	PreCondit = { fg = text, bg = C.none },
	Type = { fg = text, bg = C.none },
	StorageClass = { fg = text, bg = C.none },
	Structure = { fg = text, bg = C.none },
	Typedef = { fg = text, bg = C.none },
	Special = { fg = text, bg = C.none },
	SpecialComment = { fg = text, bg = C.none },
	Error = { fg = C.gray_50, bg = C.none },
	Todo = { fg = C.gray_50, bg = C.none },
	Underlined = { fg = C.gray_50, bg = C.none },
	Cursor = { fg = text, bg = C.none },
	ColorColumn = { fg = C.gray_50, bg = C.gray_700 },
	CursorLineNr = { fg = C.gray_200, bg = C.gray_700 },
	Conceal = { fg = C.gray_50, bg = C.none },
	CursorColumn = { fg = C.none, bg = C.none },
	CursorLine = { fg = C.none, bg = C.gray_700 },
	Directory = { fg = C.gray_50, bg = C.none },
	DiffAdd = { fg = C.green_50, bg = C.green_900 },
	DiffChange = { fg = C.gray_50, bg = C.none },
	DiffDelete = { fg = C.red_50, bg = C.red_900 },
	DiffText = { fg = C.yellow_50, bg = C.yellow_900 },
	ErrorMsg = { fg = C.gray_50, bg = C.none },
	WinSeparator = { fg = C.gray_700, bg = bg },
	Folded = { fg = text, bg = C.none },
	FoldColumn = { fg = C.none, bg = C.none },
	IncSearch = { link = "Search" },
	CurSearch = { link = "Search" },
	LineNr = { fg = C.gray_600, bg = C.none },
	NonText = { fg = C.gray_800, bg = C.none },
	Pmenu = { fg = text, bg = bg },
	PmenuSel = { fg = C.none, bg = C.gray_700 },
	PmenuSbar = { fg = C.none, bg = C.gray_600 },
	PmenuThumb = { fg = C.none, bg = C.gray_300 },
	Question = { fg = C.gray_50, bg = C.none },
	QuickFixLine = { fg = C.gray_50, bg = C.yellow },
	Search = { fg = bg, bg = text },
	SignColumn = { fg = C.none, bg = C.none },
	SpecialKey = { fg = C.fg, bg = C.none },
	SpellBad = { undercurl = true },
	SpellCap = { undercurl = true },
	SpellLocal = { undercurl = true },
	SpellRare = { undercurl = true },
	StatusLine = { fg = C.gray_200, bg = C.gray_700 },
	StatusLineExtra = { link = "StatusLine" },
	StatusLineCenter = { fg = C.gray_200, bg = bg },
	StatusLineNC = { fg = C.gray_200, bg = bg },
	StatusLineTerm = { link = "StatusLine" },
	StatusLineTermNC = { link = "StatusLine" },
	WinBar = { fg = C.gray_700, bg = bg },
	WinBarNC = { fg = C.gray_700, bg = bg },
	TabLine = { fg = C.gray_20, bg = bg },
	TabLineSel = { fg = C.gray_50, bg = C.none },
	TabLineFill = { fg = C.none, bg = bg },
	Terminal = { fg = text, bg = bg },
	Visual = { fg = C.none, bg = C.gray_700 },
	VisualNOS = { fg = C.none, bg = C.gray_700 },
	WarningMsg = { fg = C.yellow_600, bg = C.none },
	WildMenu = { link = "PmenuSel" },
	EndOfBuffer = { fg = C.gray_600, bg = C.none },
	FloatBorder = { fg = C.grey_300, bg = bg },
	MatchParen = { fg = C.none, bg = C.gray_500 },
}

return base
