return {
	TelescopeResultsTitle = { fg = C.none },
	TelescopePromptTitle = { fg = C.none },
	TelescopePreviewTitle = { fg = C.none },
	TelescopeResultsBorder = { fg = C.none },
	TelescopePromptBorder = { fg = C.none },
	TelescopePreviewBorder = { fg = C.none },
	TelescopeSelectionCaret = { fg = C.none },
	TelescopeMatching = { fg = C.gray_200 },
	TelescopeSelection = { bg = C.gray_700 },
	TelescopeMultiSelection = { fg = C.none },
	TelescopeMultiIcon = { fg = C.none },
	TelescopeNormal = { fg = C.none, bg = C.none },
	TelescopePreviewNormal = { fg = C.none, bg = C.none },
	TelescopePromptNormal = { fg = C.none, bg = C.none },
	TelescopeResultsNormal = { fg = C.none, bg = C.none },
	TelescopeBorder = { fg = C.gray_500 },
	TelescopeTitle = { fg = C.gray_300 },
	TelescopePromptCounter = { fg = C.none },
	TelescopePromptPrefix = { fg = C.none },
	TelescopePreviewLine = { bg = C.none },
	TelescopePreviewMatch = { fg = C.none },
	TelescopePreviewPipe = { fg = C.none },
	TelescopePreviewCharDev = { fg = C.none },
	TelescopePreviewDirectory = { fg = C.none },
	TelescopePreviewBlock = { fg = C.none },
	TelescopePreviewLink = { fg = C.none },
	TelescopePreviewSocket = { fg = C.none },
	TelescopePreviewRead = { fg = C.none },
	TelescopePreviewWrite = { fg = C.none },
	TelescopePreviewExecute = { fg = C.none },
	TelescopePreviewHyphen = { fg = C.none },
	TelescopePreviewSticky = { fg = C.none },
	TelescopePreviewSize = { fg = C.none },
	TelescopePreviewUser = { fg = C.none },
	TelescopePreviewGroup = { fg = C.none },
	TelescopePreviewDate = { fg = C.none },
	TelescopePreviewMessage = { fg = C.none },
	TelescopePreviewMessageFillchar = { fg = C.none },
	TelescopeResultsClass = { fg = C.none },
	TelescopeResultsConstant = { fg = C.none },
	TelescopeResultsField = { fg = C.none },
	TelescopeResultsFunction = { fg = C.none },
	TelescopeResultsMethod = { fg = C.none },
	TelescopeResultsOperator = { fg = C.cyan },
	TelescopeResultsStruct = { fg = C.none },
	TelescopeResultsVariable = { fg = C.none },
	TelescopeResultsLineNr = { fg = C.none },
	TelescopeResultsIdentifier = { fg = C.none },
	TelescopeResultsNumber = { fg = C.orange },
	TelescopeResultsComment = { fg = C.none },
	TelescopeResultsSpecialComment = { fg = C.none },
	TelescopeResultsDiffChange = { fg = C.none, bg = C.none },
	TelescopeResultsDiffAdd = { fg = C.none, bg = C.none },
	TelescopeResultsDiffDelete = { fg = C.none, bg = C.none },
	TelescopeResultsDiffUntracked = { fg = C.none, bg = C.none },
}
