CONFIG_PATH = vim.fn.stdpath "config"
DATA_PATH = vim.fn.stdpath "data"
CACHE_PATH = vim.fn.stdpath "cache"
TERMINAL = vim.fn.expand "$TERMINAL"

require "tdfirth.options"
require "tdfirth.statusline"
require "tdfirth.keymaps"
require "tdfirth.plugins"
require "tdfirth.colorscheme"
require "tdfirth.utils"
require "tdfirth.cmp"
require "tdfirth.lsp"
require "tdfirth.telescope"
require "tdfirth.treesitter"
require "tdfirth.autopairs"
